// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface MockChainLink$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "MockChainLink";
  readonly sourceName: "contracts/mock/MockChainLink.sol";
  readonly abi: [{"inputs":[{"internalType":"int256","name":"_answer","type":"int256"},{"internalType":"uint256","name":"_updatedAt","type":"uint256"}],"stateMutability":"nonpayable","type":"constructor"},{"inputs":[],"name":"answer","outputs":[{"internalType":"int256","name":"","type":"int256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"latestRoundData","outputs":[{"internalType":"uint80","name":"","type":"uint80"},{"internalType":"int256","name":"","type":"int256"},{"internalType":"uint256","name":"","type":"uint256"},{"internalType":"uint256","name":"","type":"uint256"},{"internalType":"uint80","name":"","type":"uint80"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"updatedAt","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x6080604052348015600e575f5ffd5b50604051610128380380610128833981016040819052602b916037565b5f919091556001556058565b5f5f604083850312156047575f5ffd5b505080516020909101519092909150565b60c4806100645f395ff3fe6080604052348015600e575f5ffd5b5060043610603a575f3560e01c80637519ab5014603e57806385bb7d69146059578063feaf968c146060575b5f5ffd5b604660015481565b6040519081526020015b60405180910390f35b60465f5481565b5f805460015460408051848152602081019390935282018390526060820152608081019190915260a001605056fea2646970667358221220d2f92353844e458ad592e476acdf29de7a01608695b019d00434420eee83821564736f6c634300081c0033";
  readonly deployedBytecode: "0x6080604052348015600e575f5ffd5b5060043610603a575f3560e01c80637519ab5014603e57806385bb7d69146059578063feaf968c146060575b5f5ffd5b604660015481565b6040519081526020015b60405180910390f35b60465f5481565b5f805460015460408051848152602081019390935282018390526060820152608081019190915260a001605056fea2646970667358221220d2f92353844e458ad592e476acdf29de7a01608695b019d00434420eee83821564736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/mock/MockChainLink.sol";
  readonly buildInfoId: "solc-0_8_28-12cf6351062c2901ebc9457afea34be2ad900f64";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["MockChainLink"]: MockChainLink$Type;
    ["contracts/mock/MockChainLink.sol:MockChainLink"]: MockChainLink$Type;
  }
}