services:
  db:
    image: postgres
    container_name: doc-database

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: doc-123
      POSTGRES_DB: doc-database

    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: web3@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
